/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-09-21 14:01:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar", Long.valueOf(1442485152221L));
    _jspx_dependants.put("jar:file:/C:/Users/bilbowm/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FJWA/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1386809624000L));
    _jspx_dependants.put("jar:file:/C:/Users/bilbowm/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FJWA/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1386809624000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  \r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>\r\n");
      out.write("    </title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!-- Le styles -->\r\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("      body { padding-top: 60px; /* 60px to make the container go all the way\r\n");
      out.write("      to the bottom of the topbar */ }\r\n");
      out.write("    </style>\r\n");
      out.write("    <link href=\"assets/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\">\r\n");
      out.write("      </script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <!-- Le fav and touch icons -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/ico/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"assets/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"assets/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"assets/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("    <style>\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"assets/js/gl.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body  onload=\"glrun('triangles',true);updateBombs()\">\r\n");
      out.write("    <div class=\"navbar navbar-fixed-top navbar-inverse\">\r\n");
      out.write("      <div class=\"navbar-inner\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a class=\"brand\" href=\"addGoal.html\">\r\n");
      out.write("            Get started\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav\">\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div id=\"left_panel\" class=\"hero-unit\"  style=\"float: left; display: inline;\">\r\n");
      out.write("   \r\n");
      out.write("          \r\n");
      out.write("<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boom}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("<div>\r\n");
      out.write("        \r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addBomb.html\"  onclick=\"updateBombs()\">\r\n");
      out.write("          Add Bomb\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"defuse.html\">\r\n");
      out.write("          defuse!\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("         <a class=\"btn btn-primary\" href=\"cleanUp.html\">\r\n");
      out.write("          Collect Garbage\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <!--  - <a class=\"btn btn-primary\" href=\"#\" onclick=\"updateBombs()\">\r\n");
      out.write("          Update\r\n");
      out.write("        </a> -->\r\n");
      out.write("       <p id=\"error_log\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errors}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("        <p id=\"update_test\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bombs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("      <div style=\"float: left; display: inline;\">\r\n");
      out.write("       <canvas id=\"gl\">\r\n");
      out.write("            \r\n");
      out.write("        </canvas>\r\n");
      out.write("        <br/>\r\n");
      out.write("<form id=\"myForm\">\r\n");
      out.write("<button type=\"button\" onclick=\"glrun('triangles',false)\">GL_TRIANGLES</button>\r\n");
      out.write("<button type=\"button\" onclick=\"glrun('wireframe',false)\">GL_LINE_STRIP</button>\r\n");
      out.write("<button type=\"button\" onclick=\"glrun('points',false)\">GL_POINTS</button>\r\n");
      out.write("<button type=\"button\" onclick=\"toggleBackground()\">Background</button>\r\n");
      out.write("<button type=\"button\" onclick=\"showLog()\">See Log</button>\r\n");
      out.write("</form>\r\n");
      out.write("   \r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function updateBombs() {\r\n");
      out.write("    \t//alert(\"Update\");//.setAttribute(\"update_test\", \"updated\");\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\t\t$(document).ready(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$.getJSON('");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("', {\r\n");
      out.write("\t\t\t\t\tajax : 'true'\r\n");
      out.write("\t\t\t\t}, function(data){\r\n");
      out.write("\t\t\t\t\tvar html = '';\r\n");
      out.write("\t\t\t\t\tvar len = data.length;\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < len; i++) {\r\n");
      out.write("\t\t\t\t\t\thtml += '<br/>' + data[i].description;//.toString\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('p#update_test').html(html);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t window.requestAnimationFrame(updateBombs);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("    <script src=\"jquery.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("     <script src=\"http://malsup.github.com/jquery.form.js\"></script> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"assets/js/bootstrap.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/boom.jsp(105,15) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f0.setValue("updateBombs.json");
    int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
      if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
    }
    return false;
  }
}
